import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen max-w-2xl mx-auto px-4 py-8 prose prose-slate">
      <Link href="/" className="text-soft-600 hover:underline text-sm no-underline">
        ← SoftSend
      </Link>
      <h1 className="text-2xl font-bold mt-4">Terms of Service</h1>
      <p className="text-sm text-slate-500">Last updated: September 25, 2026</p>

      <h2>Service</h2>
      <p>
        SoftSend provides AI-powered message rewriting. Credits are non-refundable 
        once used. Unused credits do not expire.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Do not use SoftSend to generate harmful, illegal, or abusive content. 
        We reserve the right to refuse service.
      </p>

      <h2>Disclaimer</h2>
      <p>
        Rewrites are generated by AI and may not be perfect. You are responsible 
        for reviewing and using the output appropriately.
      </p>

      <h2>Contact</h2>
      <p>
        Questions? Contact support@softsend.app (replace with your real email).
      </p>
    </main>
  );
}
